openapi: 3.0.3
info:
  title: 微服务
  version: "1.0"
servers:
- url: http://localhost:8000/starter
  description: 微服务
paths:
  /api/user/get_captcha_image:
    post:
      tags:
      - User
      summary: 获取图形验证码
      description: 获取图形验证码
      operationId: User#GetCaptchaImage
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCaptchaImageResponseBody'
              example:
                data:
                  captchaId: Sequi ad recusandae harum sunt culpa aliquid.
                  image: Eos quae rerum provident.
                errcode: 0
                errmsg: ""
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /api/user/login_by_username:
    post:
      tags:
      - User
      summary: 使用账号密码登录
      description: 使用账号密码登录
      operationId: User#LoginByUsername
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginByUsernameRequestBody'
            example:
              captchaId: ge
              humanCode: j8t
              password: password
              username: user
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginByUsernameResponseBody'
              example:
                data:
                  credentials:
                    expires_in: 25200
                    token: eyJhbGciOiJIUz...
                  user:
                    id: Sit praesentium beatae dignissimos blanditiis voluptas ut.
                    mobile: Repellat ea.
                    username: Sed fugit sint ex nulla.
                errcode: 0
                errmsg: ""
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /api/user/update_password:
    post:
      tags:
      - User
      summary: 修改登录密码
      description: 修改登录密码
      operationId: User#UpdatePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordRequestBody'
            example:
              new_password: abc123
              old_password: 123abc
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatePasswordResponseBody'
              example:
                data:
                  ok: true
                errcode: 0
                errmsg: ""
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - role:user
        - role:admin
components:
  schemas:
    Captcha:
      type: object
      properties:
        captchaId:
          type: string
          description: 验证码ID
          example: Dolorum veniam voluptatem accusamus.
        image:
          type: string
          description: 图片base64
          example: Unde ea est eos iusto nemo.
      example:
        captchaId: Atque dolorum optio.
        image: Vitae tempore a dicta nihil animi.
      required:
      - image
      - captchaId
    Credentials:
      type: object
      properties:
        expires_in:
          type: integer
          description: 有效时长（秒）：生成之后x秒内有效
          example: 25200
          format: int64
        token:
          type: string
          description: JWT token
          example: eyJhbGciOiJIUz...
      example:
        expires_in: 25200
        token: eyJhbGciOiJIUz...
      required:
      - token
      - expires_in
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GetCaptchaImageResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Captcha'
        errcode:
          type: integer
          description: 错误码
          example: 0
          minimum: 0
          maximum: 999999
        errmsg:
          type: string
          description: 错误消息
          example: ""
      example:
        data:
          captchaId: Sequi ad recusandae harum sunt culpa aliquid.
          image: Eos quae rerum provident.
        errcode: 0
        errmsg: ""
      required:
      - errcode
      - errmsg
    LoginByUsernameRequestBody:
      type: object
      properties:
        captchaId:
          type: string
          description: 图形验证码ID
          default: ""
          example: 3l
          minLength: 1
          maxLength: 128
        humanCode:
          type: string
          description: 图形验证码
          default: ""
          example: 14h
          minLength: 4
          maxLength: 8
        password:
          type: string
          description: 密码
          example: password
          minLength: 1
          maxLength: 128
        username:
          type: string
          description: 用户名
          example: user
          minLength: 1
          maxLength: 128
      example:
        captchaId: "y"
        humanCode: pgd
        password: password
        username: user
      required:
      - username
      - password
    LoginByUsernameResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Session'
        errcode:
          type: integer
          description: 错误码
          example: 0
          minimum: 0
          maximum: 999999
        errmsg:
          type: string
          description: 错误消息
          example: ""
      example:
        data:
          credentials:
            expires_in: 25200
            token: eyJhbGciOiJIUz...
          user:
            id: Sit praesentium beatae dignissimos blanditiis voluptas ut.
            mobile: Repellat ea.
            username: Sed fugit sint ex nulla.
        errcode: 0
        errmsg: ""
      required:
      - errcode
      - errmsg
    Session:
      type: object
      properties:
        credentials:
          $ref: '#/components/schemas/Credentials'
        user:
          $ref: '#/components/schemas/User'
      description: 会话
      example:
        credentials:
          expires_in: 25200
          token: eyJhbGciOiJIUz...
        user:
          id: Sit praesentium beatae dignissimos blanditiis voluptas ut.
          mobile: Repellat ea.
          username: Sed fugit sint ex nulla.
      required:
      - user
      - credentials
    Successresult:
      type: object
      properties:
        ok:
          type: boolean
          description: success
          example: true
      description: 成功信息
      example:
        ok: true
      required:
      - ok
    UpdatePasswordRequestBody:
      type: object
      properties:
        new_password:
          type: string
          example: abc123
          minLength: 6
          maxLength: 128
        old_password:
          type: string
          example: 123abc
          minLength: 1
          maxLength: 128
      example:
        new_password: abc123
        old_password: 123abc
      required:
      - old_password
      - new_password
    UpdatePasswordResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Successresult'
        errcode:
          type: integer
          description: 错误码
          example: 0
          minimum: 0
          maximum: 999999
        errmsg:
          type: string
          description: 错误消息
          example: ""
      example:
        data:
          ok: true
        errcode: 0
        errmsg: ""
      required:
      - errcode
      - errmsg
    User:
      type: object
      properties:
        id:
          type: string
          description: ID
          example: Sapiente sed.
        mobile:
          type: string
          description: 手机号
          example: Adipisci ad rerum officiis tempore placeat.
        username:
          type: string
          description: 用户名
          example: Facilis harum quaerat consectetur recusandae et.
      description: 用户
      example:
        id: Nobis veritatis.
        mobile: Non sed.
        username: Voluptatum aut impedit molestiae aut minus.
      required:
      - id
      - username
      - mobile
  securitySchemes:
    jwt_header_Authorization:
      type: http
      description: JWT 认证
      scheme: bearer
